apps/board/models.py
from datetime import datetime
from apps.app import db

class Board(db.Model):
  __tablename__ = 'board'
  id = db.Column(db.Integer, primary_key=True)   # primary_key=True : 기본키 컬럼
  subject = db.Column(db.String(255), nullable=False)
  content = db.Column(db.Text(), nullable=False)
  created_at = db.Column(db.DateTime, default=datetime.now)
  updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)
  user_id = db.Column(db.Integer, db.ForeignKey("users.id", ondelete='CASCADE'), nullable=False)
  # ondelete='CASCADE' : 부모 행 삭제 시 외래 키를 참조하는 자식 행도 함께 삭제
  
  # 양방향 참조 - 컬럼명 : user
  # 별도 join이나 select 없이 user로 board 정보, board로 user 정보 받을 수 있음
  # backref : 역참조 -> user에서 board 정보를 가져오기 위한 'boards' 생성
  user = db.relationship('User', backref = db.backref('boards'))

class Comment(db.Model):
  __tablename__ = 'comment'
  id = db.Column(db.Integer, primary_key=True)
  content = db.Column(db.Text, nullable=False)
  created_at = db.Column(db.DateTime, default=datetime.now)
  updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)
  user_id = db.Column(db.Integer, db.ForeignKey('users.id', ondelete='CASCADE'), nullable=False)
  user = db.relationship('User', backref = db.backref('user_comments'))
  board_id = db.Column(db.Integer, db.ForeignKey('board.id', ondelete='CASCADE'), nullable=False)
  board = db.relationship('Board', backref = db.backref('comment_list'))
  
  
  

apps/board/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField, TextAreaField
from wtforms.validators import DataRequired

class BoardForm(FlaskForm):
  subject = StringField(
    "제목",
    validators=[DataRequired('제목을 입력하세요.')]
  )
  
  content = TextAreaField(
    "내용",
    validators=[DataRequired('내용을 입력하세요.')],
    render_kw={'rows': 10} 
    )
  
  submit = SubmitField('등록')

class DeleteForm(FlaskForm):
  submit = SubmitField('삭제')
  
class CommentForm(FlaskForm):
  content  = TextAreaField(
    "댓글",
    validators=[DataRequired('댓글을 입력하세요.')]
    )
  submit = SubmitField('등록')

apps/board/__init__.py
import apps.board.models

apps/board/views.py
from flask import Blueprint, render_template, redirect, url_for, request, jsonify
from flask_login import login_required, current_user

from apps.app import db
from apps.crud.models import User
from apps.board.models import Board, Comment
from apps.board.forms import BoardForm, DeleteForm, CommentForm

board = Blueprint( 
  'board',
  __name__,
  template_folder='templates/board',
  static_folder='static'
)

comment = Blueprint(
  'comment',
  __name__,
  template_folder='templates/board',
  static_folder='static'
)

# 임시 게시글 300개 추가 / url에 dummy 입력하면 자동 생성됨
# @board.route('/dummy')
# def make_dummy():
#   for i in range(300):
#     board=Board(
#     subject = f'임시제목{i}',
#     content = f'임시내용{i}',
#     user_id = 1
#     )
#     db.session.add(board)
#     db.session.commit()    

@board.route('/')
def index(): 
  #몇 페이지를 보려고 하는지 저장
  page = request.args.get('page', type=int, default=1)    # 페이지 번호
  boards = Board.query.order_by(Board.created_at.desc()).paginate(page=page, per_page=10)
  

  
  print('------------------------------')
  print('현재 페이지의 레코드', boards.items)
  print('전체 수', boards.total)
  print('페이지 당 표시할 레코드 수', boards.per_page)
  print('현재 페이지 번호', boards.page)
  print('페이지 범위', boards.iter_pages)
  print('이전 페이지 번호', boards.prev_num)
  print('다음 페이지 번호', boards.next_num)
  print('이전 페이지 있나?', boards.has_prev)
  print('다음 페이지 있나?', boards.has_next)
  print('------------------------------')
   
  return render_template('index.html', boards=boards)

@board.route('/new', methods=['GET', 'POST'])
@login_required
def new_board():
  form = BoardForm()
  
  if form.validate_on_submit():
    board = Board(
        user_id=current_user.id,
        subject=form.subject.data,
        content=form.content.data
    )
    db.session.add(board)
    db.session.commit()
    
    return redirect(url_for('board.index'))
    
  return render_template('new.html', form=form)

@board.route('/detail/<int:board_id>', methods=['GET', 'POST'])
@login_required
def detail_board(board_id):
  board = Board.query.get_or_404(board_id)
  form = CommentForm()

  if form.validate_on_submit():
    new_comment = Comment(
        user_id=current_user.id,
        content=form.content.data,
        board_id=board.id
    )
    db.session.add(new_comment)
    db.session.commit()
    
    return redirect(url_for('board.detail_board', board_id=board.id, comment=comment))

  return render_template('detail.html', board=board, form=form)  # jinja로 보내줌

@board.route('/update/<int:board_id>', methods=['GET','POST'])
def board_edit(board_id):
  board = Board.query.get_or_404(board_id)
  form = BoardForm(obj = board)
  
  if form.validate_on_submit():
    board.subject = form.subject.data
    board.content = form.content.data
      
    db.session.add(board)
    db.session.commit()
  
    return redirect(url_for('board.detail_board', board_id=board_id))
  
  return render_template ('edit.html', board=board, form=form)

# @board.route('/update', methods=['POST'])
# @login_required
# def update_board():
#   form = BoardForm()

#   return render_template('update.html', form=form)

@board.route('/delete/<int:board_id>', methods=['GET','POST'])
@login_required
def delete_board(board_id):
  board = Board.query.get(board_id)
  db.session.delete(board)
  db.session.commit()
    
  return redirect(url_for('board.index'))
    
@comment.route('/new/<board_id>', methods=['POST'])
@login_required
def new_comment(board_id):
  content = request.form['content']
  comment = Comment(content=content, user_id=current_user.id, board_id=board.id)

  db.session.add(comment)
  db.session.commit()
    
  return redirect(url_for('board.detail_board', board_id=board.id))

@comment.route('/detail/<int:board_id>')
def comment_list():
  comments = Comment.query.filter_by(board_id=board.id).order_by(Comment.created_at.desc()).all()
  form = CommentForm()
  
  if form.validate_on_submit():
    new_comment = Comment(content=form.content.data, board_id=board.id, user_id=current_user.id)
    db.session.add(new_comment)
    db.session.commit()
    return redirect(url_for('comment.comment_list', board_id=board.id))
 
  return render_template('detail.html', form=form, board=board, comments=comments)

@comment.route('/<comment_id>', methods=['PUT'])
@login_required
def edit_comment(comment_id):
  data = request.json # client가 요청하면 body에 담간 data 받아옴 ->수정할 댓글 내용
  comment = Comment.query.get(comment_id) # db에 수정할 댓글 id에 해당되는 레코드 추출 
 
  comment.content = data.get('content')
  
  try:
    db.session.commit()
    return jsonify({
      'message': '댓글 수정 완료',
      'content': comment.content,
      'status':'success'
    }), 200
  except Exception as e:
    db.session.rollback()
    return jsonify({'message' : '댓글 수정 실패', 'status' : 'error'}), 500
  
  # board = Board.query.get_or_404(comment.board_id)  # comment의 board_id를 이용하여 Board 객체를 조회
  # form = CommentForm(obj=comment)

  # if form.validate_on_submit():
  #   comment.content = form.content.data

  #   return redirect(url_for('board.detail_board', board_id=board.id))

  # return render_template('detail.html', form=form, board=board, comment=comment)

# detail.html에서 jinja로 comment_id 보내면 views.py의 route도 comment_id로 받아야 함
@comment.route('/<comment_id>', methods=['DELETE'])
@login_required
def delete_comment(comment_id):
  comment = Comment.query.get_or_404(comment_id)

  try:
    db.session.delete(comment)
    db.session.commit()
    
    return jsonify({'message' : '댓글 삭제 완료'}), 200
  except Exception as e:
    db.session.rollback()
   
    return jsonify({'message' : '댓글 삭제 실패'}), 500

apps/board/templates/board/detail.html
{% extends "detector/base.html" %}

{% block content %}

<div class="mb-3">
  <label class="form-label">제목</label>
  <input class="form-control" type="text" value="{{ board.subject }}" readonly>
</div>
<!-- input 태그는 원래 입력받는 창인데 내용을 보여주기만 하려면 readonly 추가 -->

<p>작성자 : {{ board.user.username }}</p>
<p>작성일 : {{ board.created_at }}</p>

<div class="mb-3">
  <label class="form-label">내용</label>
  <textarea class="form-control" rows="10" readonly>{{ board.content }}</textarea>
</div>

<div>
  <a href="{{ url_for('board.board_edit', board_id=board.id) }}" class="btn btn-primary"
    style="background-color: rgb(45, 111, 47); border-color: antiquewhite;">내용 수정</a>
  <a href="{{ url_for('board.delete_board', board_id=board.id) }}" class="btn btn-danger delete-board"
    style="background-color: rgb(148, 64, 78); border-color: antiquewhite;">삭제</a>
</div>

<hr>

<div>
  <h5>댓글 [{{ board.comment_list|length }}]</h5>
  <div class="comment-list">
    {% for comment in board.comment_list %}
    <li class="list-group-item d-flex justify-content-between align-items-center" id="comment-{{ comment.id }}">
      <div>
        <p class="mb-1">작성자 : {{ comment.user.username }}</p>
        <p class="mb-1" id="content-text-{{ comment.id }}">{{ comment.content }}</p>
        <textarea class="form-control d-none" id="content-edit-{{ comment.id }}">{{ comment.content }}</textarea>
        <p>작성일 : {{ comment.created_at }}</p>
      </div>
      <div class="btn-group">
        <button class="btn btn-sm btn-primary edit-comment-btn" data-comment-id="{{comment.id}}">수정</button>
        <button class="btn btn-sm btn-success save-comment-btn d-none" data-comment-id="{{comment.id}}">저장</button>
        <button class="btn btn-sm btn-danger" onclick="deleteComment('{{comment.id}}')">삭제</button>
      </div>
    </li>
    <hr>
    {% endfor %}
    <form action="{{ url_for('comment.new_comment', board_id=board.id) }}" method="post">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
      <textarea class="form-control" name="content" rows="3"></textarea>
      <input class="btn btn-primary mt-3" type="submit" value="등록">
    </form>
  </div>
</div>
<!-- detail.html에서 jinja로 comment_id 보내면 views.py의 route도 comment_id로 받아야 함 -->

{% endblock %}

{% block script %}
<script src="{{url_for('board.static', filename='js/comment.js')}}"></script>
{% endblock %}

apps/board/templates/board/edit.html
{% extends "detector/base.html" %}

{% block content %}

<form action="{{ url_for('board.board_edit', board_id=board.id) }}" method="post" novalidate>
  {{form.csrf_token}}

  {% for field in form %}
  {% for error in field.errors %}
  <p class="alert alert-danger">{{error}}</p>
  {% endfor %}
  {% endfor %}

  <div>
    {{form.subject.label}}
    {{form.subject(class='form-control')}}
  </div>

  <div>
    {{form.content.label}}
    {{form.content(class='form-control')}}
  </div>

  {{ form.submit(class="btn btn-primary mt-3")}}
</form>

{% endblock %}

<!-- <div>
  <h3>제목 : </h3>{{ boards.subject }}<br>
  <p>작성자: </p>{{ boards.user.id }}<br>
  <p>내용 : </p>{{ boards.content }}<br>

  <a href="{{ url_for('board.detail', board_id=board.id) }}">자세히 보기</a>
</div> -->

apps/board/templates/board/index.html
{% extends "detector/base.html" %}

{% block content %}
<h3>게시판</h3>

<div class="container my-3">
  <a class="btn btn-primary mb-3" href="{{url_for('board.new_board')}}">글 작성</a>
</div>

<table class="table">
  <thead>
  <tbody>
    {% for board in boards %}
    <tr>
      <td>{{ board.id }}</td>
      <td>
        <a href="{{ url_for('board.detail_board', board_id = board.id) }}">{{ board.subject }}</a>
      </td>
      <td>{{ board.user.username }}</td>
      <td>{{ board.created_at }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<div class="pagination">
  {% for page in range(1, boards.pages + 1) %}
    {% if page == boards.page %}
      <span class="active">{{ page }}</span>
    {% else %}
      <a href="{{ url_for('board.index', page=page) }}">{{ page }}</a>
    {% endif %}
  {% endfor %}
</div>

{% endblock %}

apps/board/templates/board/new.html
{% extends "detector/base.html" %}

{% block content %}

<div>
  <form action="{{ url_for ('board.new_board') }}" method="post" enctype="multipart/form-data" novalidate>
    {{form.csrf_token}}

    {% for field in form %}
      {% for error in field.errors %}
         <p class="alert alert-danger">{{error}}</p>
      {% endfor %}
    {% endfor %}

    <div>
      {{form.subject.label}}
      {{form.subject(class='form-control')}}
    </div>

    <div>
      {{form.content.label}}
      {{form.content(class='form-control')}}
    </div>

    {{ form.submit(class="btn btn-primary mt-3")}}
  </form>
</div>

{% endblock %}

<!-- <div>
  <h3>제목 : </h3>{{ boards.subject }}<br>
  <p>작성자: </p>{{ boards.user.id }}<br>
  <p>내용 : </p>{{ boards.content }}<br>

  <a href="{{ url_for('board.detail', board_id=board.id) }}">자세히 보기</a>
</div> -->

apps/board/templates/board/update.html
{% extends "detector/base.html" %}

{% block content %}

<div>
  <form action="{{ url_for ('board.update_board') }}" method="post" enctype="multipart/form-data" novalidate>
    {{form.csrf_token}}

    <div>
      {{ form.image(class="form-control-file") }}
    </div>
    <div>
      {% for error in form.image.errors %}
      <span style="color: red;">{{ error }}</span>
      {% endfor %}
    </div>
    {{ form.submit(class="btn btn-primary")}}
  </form>
</div>

{% endblock %}