apps/crud/models.py
from datetime import datetime

from apps.app import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

class User(db.Model, UserMixin):
  # 테이블명 설정
  __tablename__ = 'users'
  # 컬럼 설정
  id = db.Column(db.Integer, primary_key=True)
  username = db.Column(db.String(255), index=True)
  email = db.Column(db.String(255), unique=True, index=True)
  password_hash = db.Column(db.String(255))
  created_at = db.Column(db.DateTime, default=datetime.now)
  updated_at = db.Column(db.DateTime, default=datetime.now, onupdate=datetime.now)

  @property
  def password(self):
    raise AttributeError('비밀번호는 접근이 불가능 합니다.')

  @password.setter
  def password(self, password):
    self.password_hash = generate_password_hash(password)

  def verify_password(self, password):
    return check_password_hash(self.password_hash, password)
  
  def is_duplicate_email(self):
    return User.query.filter_by(email = self.email).first() is not None
  
@login_manager.user_loader
def load_user(user_id):
  return User.query.get(user_id)

apps/crud/forms.py
from flask_wtf import FlaskForm
from wtforms import PasswordField, StringField, SubmitField
from wtforms.validators import length, DataRequired, Email

class UserForm(FlaskForm):
  username = StringField(
    "사용자명",
    validators=[
      DataRequired(message='사용자명은 필수입니다.'),
      length(max=30, message='30자 이하로 입력하세요')
    ]
  )

  email = StringField(
    "메일주소",
    validators=[
      DataRequired(message='이메일은 필수로 입력'),
      Email(message='메일 주소 형식으로 입력')
    ]
  )

  password = PasswordField(
    "비밀번호",
    validators=[
      DataRequired(message='비밀번호는 반드시 입력')
    ]
  )

  submit = SubmitField("회원가입")

apps/crud/__init__.py
import apps.crud.models

apps/crud/views.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_required

from apps.crud.forms import UserForm
from apps.crud.models import User
from apps.app import db

crud = Blueprint(
  "crud",
  __name__,
  template_folder="templates",
  static_folder="static"
)

@crud.route('/')
def index():
  return render_template('crud/index.html')

@crud.route('/users/new', methods=["GET", "POST"])
@login_required
def create_user():
  form = UserForm()

  if form.validate_on_submit():
    # db에 저장할 객체 설정
    user = User(
      username = form.username.data,
      email = form.email.data,
      password = form.password.data
    )
    # db에 insert 시키고
    db.session.add(user)
    db.session.commit()

    # 회원가입 완료 페이지 이동
    return redirect(url_for('crud.users'))
  
  return render_template('crud/create.html', form=form)

@crud.route('/users')
@login_required
def users():
  # 회원정보들을 db에서 가져오는 코드
  users = User.query.all()

  return render_template('crud/index.html', users=users)

@crud.route('/users/<user_id>', methods=['GET', 'POST'])
@login_required
def user_edit(user_id):
    form = UserForm()
    user = User.query.filter_by(id=user_id).first()
    
    if form.validate_on_submit():
      user.username = form.username.data
      user.email = form.email.data
      user.password = form.password.data      
      
      db.session.add(user)
      db.session.commit()
      
      return redirect(url_for('crud.users'))

    return render_template('crud/edit.html', user=user, form=form)


@crud.route('/users/<user_id>/delete', methods=['POST'])
@login_required
def delete_user(user_id):
  # User = User.query.filter_by(id = user_id).delete()
  # db.session.commit()
    user = User.query.filter_by(id=user_id).first()
    db.session.delete(user)
    db.session.commit()

    return redirect(url_for('crud.users'))

apps/crud/templates/crud/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  {% if current_user.is_authenticated %}
  <div>
    <span>{{ current_user.username }}</span>
    <span><a href="{{url_for('auth.logout')}}">로그아웃</a></span>
  </div>
  {% else %}
  <div>
    <a href="{{url_for('auth.login')}}">로그인</a>
  </div>
  {% endif %}
  {% block content %}{% endblock %}
  <p>footer영역</p>
</body>
</html>

apps/crud/templates/crud/create.html
{% extends "crud/base.html" %}
{% block title %}회원가입{% endblock %}

{% block content %}
  <h1>회원가입 페이지</h1>
  <form action="{{ url_for('crud.create_user') }}", method="post" novalidate>
    {{ form.csrf_token }}

    <div>
      {{ form.username.label }}
      {{ form.username(placeholder="사용자명을 입력하세요") }}
    </div>
    {% for error in form.username.errors %}
      <span style="color: red;">{{ error }}</span>
    {% endfor %}

    <div>
      {{ form.email.label }}
      {{ form.email(placeholder="메일주소를 입력하세요") }}
    </div>
    {% for error in form.email.errors %}
      <span style="color: red;">{{ error }}</span>
    {% endfor %}

    <div>
      {{ form.password.label }}
      {{ form.password(placeholder="비밀번호를 입력하세요") }}
    </div>
    {% for error in form.password.errors %}
      <span style="color: red;">{{ error }}</span>
    {% endfor %}

    <div>
      {{ form.submit() }}
    </div>
  </form>
{% endblock %}

apps/crud/templates/crud/edit.html
{% extends "crud/base.html" %}
{% block title %}회원정보 수정{% endblock %}

{% block content %}
<h1>정보 수정 페이지</h1>
<form action="{{ url_for('crud.user_edit', user_id=user.id) }}" , method="POST" novalidate>
  {{ form.csrf_token }}

  <div>
    {{ form.username.label }}
    {{ form.username(placeholder="사용자명을 입력하세요", value=user.username) }}
  </div>
  {% for error in form.username.errors %}
  <span style="color: red;">{{ error }}</span>
  {% endfor %}

  <div>
    {{ form.email.label }}
    {{ form.email(placeholder="메일주소를 입력하세요", value=user.email) }}
  </div>
  {% for error in form.email.errors %}
  <span style="color: red;">{{ error }}</span>
  {% endfor %}

  <div>
    {{ form.password.label }}
    {{ form.password(placeholder="비밀번호를 입력하세요") }}
  </div>
  {% for error in form.password.errors %}
  <span style="color: red;">{{ error }}</span>
  {% endfor %}

  <div>
    <input type="submit" value="정보수정">
  </div>
</form>

<form action="{{url_for('crud.delete_user', user_id=user.id)}}", method="post">
  <!-- user 안에 id를 user_id라는 변수에 담아서 views.py에 user_id로 보냄 -->
  {{form.csrf_token}}
    <input type="submit" value="탈퇴">
</form>
{% endblock %}

apps/crud/templates/crud/index.html
{% extends "crud/base.html" %}
{% block title %}index페이지{% endblock %}

{% block content %}
  <h1>CRUD Index Page</h1>
  <a href="{{ url_for('crud.create_user') }}">신규 회원 등록</a>

  {% for user in users %}
    <p>
      id:{{ user.id }} / 
      username : <a href="{{ url_for('crud.user_edit', user_id = user.id)}}"> {{ user.username }} / </a>
      email : {{ user.email }}
    </p>
  {% endfor %}
{% endblock %}